### ISSUE TITLE
README instructions

### ISSUE THREAD

**Issue by encosion** [alter-alter/DelugeFirmware#10]
Could you add some basic readme instructions pretty please?

`How to install` is pretty standard for all forks, but more importantly for this one... What is it? How does it work? How do you access it? etc.

Apologies, if this is covered elsewhere!

**Comment by alter-alter** [comment]
Please check out:
https://github.com/alter-alter/DelugeFirmware

**Comment by encosion** [comment]
Amazing! Perfect thanks!

**Comment by ok-reza** [comment]
On 7-SEG, when I choose quantize or quantize all and turn LEFT instead of right, I see "H 0" - "H 99" or "HA 0" to "HA99".

What does H mean in this instance. I seem to get inconsistent results from it, or at least it seems that way.

Great work so far!

**Comment by alter-alter** [comment]
"H" stands for "Humanaize." It adds random variations to the positions of the notes. I have updated the readme.

**Comment by ok-reza** [comment]
Ah! Neat, thanks!

By the way, if you'd like to join the Deluge Discord: https://discord.gg/t9fcjuuDkx
there is a #dev-chat channel where other devs have been meeting up.
