### ISSUE TITLE
Please submit these new features as PRs on the community repo.

### ISSUE THREAD

**Issue by weavermedia** [alter-alter/DelugeFirmware#17]
Please submit these new features as separate PRs on the community repo.

**Comment by sichtbeton** [comment]
Yes, please!

**Comment by sichtbeton** [comment]
just wanting to ask again: would you be willing to offer this code to the community (via the official version)?

**Comment by alter-alter** [comment]
My implementation is quite messy, so I don't think it's suitable to be sent to the official as it is. However, the code in this repository is free to use, so it doesn't prevent someone else from submitting it to the official.

**Comment by sichtbeton** [comment]
> My implementation is quite messy, so I don't think it's suitable to be sent to the official as it is. However, the code in this repository is free to use, so it doesn't prevent someone else from submitting it to the official.

right. so you would be fine if one would submit it?

**Comment by alter-alter** [comment]
Sure, there's no problem.

**Comment by sichtbeton** [comment]
@weavermedia  could be closed?
