### ISSUE TITLE
Retriggering silent

### ISSUE THREAD

**Issue by sichtbeton** [alter-alter/DelugeFirmware#2]
When in this (awesome) view one button is held down and you press another one of the same kit item, it doesn't trigger.

It's not a huge deal. But it would be a nice addition.

**Comment by ok-reza** [comment]
That would definitely help when recording different rhythms of different velocities and such. +1

**Comment by sichtbeton** [comment]
also when you map transpose to velocity you can play polyphonically. when retrigger is possible, this allows for multiple samples being played simultaneously on one view. quite cool.

**Comment by sichtbeton** [comment]
Would this be hard to solve?
