### ISSUE TITLE
Use the random button

### ISSUE THREAD

**Issue by sichtbeton** [alter-alter/DelugeFirmware#20]
@okreza suggested this in the discord: Why not use the Random button for triggering the random function? Wouldn't interfere (probably) and would make sense.

**Comment by alter-alter** [comment]
That's a great idea. I have implemented it in the latest firmware. (Deluge-release-xxxx1051.bin)

**Comment by sichtbeton** [comment]
It was ok Rezas idea. Just to clarify. Already implemented it? Wow!
