### ISSUE TITLE
Random function left over on pad 

### ISSUE THREAD

**Issue by sichtbeton** [alter-alter/DelugeFirmware#22]
In 1.07 the random function is still using the pad right next to the clip playback direction button. This makes it more dangerous, because you can accidentally randomize the sample when you wanted to change the playback mode only.

maybe remove it as it lives in the actual random button now?

7seg / 1.07 fw

**Comment by alter-alter** [comment]
I have removed the ↓1→6 pad shortcut in version 1.0.7.4
https://github.com/alter-alter/DelugeFirmware/releases

**Comment by sichtbeton** [comment]
Nice!!
