### ISSUE TITLE
Suggestion: kit levels to transpose

### ISSUE THREAD

**Issue by sichtbeton** [alter-alter/DelugeFirmware#24]
When using the 16 levels kit view, it's possible to map transpose to velocity. This is cool, but it doesn't adhere to semitones. Is there a way to play a kit item chromatically with this view?

**Comment by weavermedia** [comment]
It can adhere to semitones in steps of 2. Velocity 64 = original pitch. Then every 2 velocity up or down is 1 semitone up or down.

Like:
...
54 = -1 octave
...
60 = -2 semitones
62 = -1 semitone
64 = no transpose
68 = +1 semitone
70 = +2 semitones
...
88 = +1 octave
...

**Comment by weavermedia** [comment]
If it was possible to do this while respecting the deleted scale for the track you could have 2 octaves of pitch in the 8x8 pad grid (for 8-note scales, which I imagine are most commonly used).

If there's no way to incorporate the scale you could have 16 notes of chromatic pitch with original pitch at bottom left.

**Comment by alter-alter** [comment]
For chromatic, try the following settings:
MasterTranspose -> Verocity : 25
OSC1 Trasnpose : 0.1

The 16-pad velocity outputs values from 7 to 127 in increments of 8  (the center is 63), so a few cents of correction is required.

**Comment by sichtbeton** [comment]
omg, thank you both! this is brilliant. works like a charm. just gotta remember those settings. cool!
