### ISSUE TITLE
Any pads in Keyboard View that aren't an assigned sample/row should be GREY

### ISSUE THREAD

**Issue by ok-reza** [alter-alter/DelugeFirmware#6]
If disabled pads (pads outside the range of the Kit) are GREY it should help the user know which pads have samples on them and which don't. This is especially helpful when there is a Kit with less than 8 sample rows assigned to it. It can be hard to know which color to press first.

I did notice that the color that is chosen before or after the last sample in the kit is what the Deluge displays when you press an audition pad outside of the enabled rows in sequencer view. However, once loaded, often times that color changes anyway.

**Comment by alter-alter** [comment]
Thank you for the feedback! I have made a fix so that out-of-range pads are displayed in gray.

**Comment by ok-reza** [comment]
Looks excellent!
